# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Example 3: Python Lambda — Serverless Framework (SNS event-driven + EventBridge cron)
#
# This example covers two Lambda functions in a single Serverless Framework service:
#   1. `process_notification` — triggered by SNS (async event-driven pattern)
#   2. `daily_report`         — triggered by EventBridge (cron / scheduled job)
#
# It uses boto3 to write results to S3 and to send emails via SES.
# This represents the "medium-to-high complexity" migration class.

import json
import os
import logging
import boto3
from datetime import datetime, timezone

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# --- AWS SDK clients ---
s3 = boto3.client('s3')
ses = boto3.client('ses', region_name='us-east-1')

REPORT_BUCKET = os.environ.get('REPORT_BUCKET', 'my-reports-bucket')
REPORT_EMAIL_FROM = os.environ.get('REPORT_EMAIL_FROM', 'reports@example.com')
REPORT_EMAIL_TO = os.environ.get('REPORT_EMAIL_TO', 'team@example.com')


def process_notification(event, context):
    """
    Triggered by SNS push. Processes each message record.
    SNS delivers records with a specific AWS event envelope:
      event['Records'][n]['Sns']['Message']
    """
    for record in event.get('Records', []):
        sns_payload = record.get('Sns', {})
        subject = sns_payload.get('Subject', 'No Subject')
        message_str = sns_payload.get('Message', '{}')

        logger.info(f"Received SNS notification: subject={subject}")

        try:
            message = json.loads(message_str)
        except json.JSONDecodeError:
            logger.warning(f"Non-JSON message body: {message_str}")
            message = {'raw': message_str}

        # Store the processed payload to S3 for audit
        timestamp = datetime.now(timezone.utc).strftime('%Y/%m/%d/%H%M%S')
        key = f"notifications/{timestamp}-{context.aws_request_id}.json"
        s3.put_object(
            Bucket=REPORT_BUCKET,
            Key=key,
            Body=json.dumps({'subject': subject, 'message': message}, indent=2),
            ContentType='application/json',
        )
        logger.info(f"Stored notification to s3://{REPORT_BUCKET}/{key}")


def daily_report(event, context):
    """
    Triggered by EventBridge Scheduler (cron). Generates a daily report,
    stores it in S3, and emails a link via SES.
    """
    today = datetime.now(timezone.utc).strftime('%Y-%m-%d')
    report_key = f"reports/daily-{today}.json"

    # Simulate building report data
    report = {
        'date': today,
        'generated_at': datetime.now(timezone.utc).isoformat(),
        'summary': 'Daily report generated by scheduled Lambda.',
        'items_processed': 42,
    }

    # Write report to S3 (lock-in!)
    s3.put_object(
        Bucket=REPORT_BUCKET,
        Key=report_key,
        Body=json.dumps(report, indent=2),
        ContentType='application/json',
    )
    logger.info(f"Report written to s3://{REPORT_BUCKET}/{report_key}")

    # Send email notification via SES (lock-in!)
    ses.send_email(
        Source=REPORT_EMAIL_FROM,
        Destination={'ToAddresses': [REPORT_EMAIL_TO]},
        Message={
            'Subject': {'Data': f'Daily Report — {today}'},
            'Body': {
                'Text': {
                    'Data': (
                        f"Your daily report for {today} is ready.\n\n"
                        f"S3 path: s3://{REPORT_BUCKET}/{report_key}\n"
                    )
                }
            },
        },
    )
    logger.info("Email notification sent via SES.")
    return {'statusCode': 200, 'body': json.dumps({'report_key': report_key})}
