#!/usr/bin/env bash
# Vendor the obra/superpowers methodology into cabral-skills at a PINNED upstream tag.
#
# Upstream: https://github.com/obra/superpowers  (MIT, Jesse Vincent)
# Third-party, vendored — do NOT hand-edit vendored/superpowers/**; re-run this script against a
# newer tag to update, then review the diff and re-tag/release.
#
# It vendors the full methodology (all skills) and pre-builds an Antigravity-appropriate
# always-on BOOTSTRAP RULE from `using-superpowers` so the DHC can materialize it verbatim
# (skills -> .agents/skills/, bootstrap-rule.md -> .agents/rules/superpowers.md).
#
# Usage:  scripts/vendor-superpowers.sh <tag>        # e.g. v6.1.1
# Requires: curl, unzip, python3. Uses `gh` to record the exact commit if available.

set -euo pipefail

REPO="obra/superpowers"
LICENSE="MIT"
TAG="${1:-}"
[ -n "$TAG" ] || { echo "usage: $0 <upstream-tag>  (e.g. v6.1.1)" >&2; exit 2; }

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/vendored/superpowers"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

echo "[vendor] Downloading ${REPO}@${TAG} ..."
curl -fsSL -o "$TMP/src.zip" "https://github.com/${REPO}/archive/refs/tags/${TAG}.zip"
unzip -q -o "$TMP/src.zip" -d "$TMP"
SRC="$(find "$TMP" -maxdepth 1 -type d -name 'superpowers-*' | head -n1)"
[ -n "$SRC" ] && [ -d "$SRC/skills" ] || { echo "[vendor] ERROR: no skills/ in ${REPO}@${TAG}" >&2; exit 1; }

echo "[vendor] Refreshing $DEST ..."
rm -rf "$DEST"; mkdir -p "$DEST"
cp -R "$SRC/skills" "$DEST/skills"
[ -f "$SRC/LICENSE" ] && cp "$SRC/LICENSE" "$DEST/LICENSE"

# Pre-build the always-on bootstrap rule from using-superpowers/SKILL.md: strip its frontmatter,
# prepend always-on frontmatter + an Antigravity skill-loading note. The DHC copies this verbatim
# to .agents/rules/superpowers.md (always-on -> loads interactive AND headless `agy -p`).
BOOT_SRC="$DEST/skills/using-superpowers/SKILL.md"
[ -f "$BOOT_SRC" ] || { echo "[vendor] ERROR: using-superpowers/SKILL.md missing" >&2; exit 1; }
python3 - "$BOOT_SRC" "$DEST/bootstrap-rule.md" <<'PY'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
body = open(src, encoding="utf-8").read()
# strip a leading YAML frontmatter block
body = re.sub(r'^---\n.*?\n---\n', '', body, count=1, flags=re.DOTALL)
header = (
    "---\n"
    "trigger: always_on\n"
    "description: Superpowers methodology bootstrap — invoke the right skill before acting; "
    "brainstorm/spec before building; get approval before code.\n"
    "---\n"
    "<!-- Vendored from obra/superpowers (MIT). Generated by scripts/vendor-superpowers.sh; do not hand-edit. -->\n\n"
    "> **Antigravity note:** you have skill discovery but no `Skill` tool. To \"invoke\" a skill, "
    "READ its `.agents/skills/<name>/SKILL.md` with the file-read tool and follow it exactly. "
    "See `.agents/skills/using-superpowers/references/antigravity-tools.md`.\n\n"
)
open(dst, "w", encoding="utf-8").write(header + body)
print(f"[vendor] wrote {dst}")
PY

COMMIT="$(gh api "repos/${REPO}/git/ref/tags/${TAG}" --jq '.object.sha' 2>/dev/null || echo "")"
SKILLS_JSON="$(cd "$DEST/skills" && ls -d */ 2>/dev/null | sed 's#/##' | python3 -c 'import sys,json;print(json.dumps(sorted(l.strip() for l in sys.stdin if l.strip())))')"

echo "[vendor] Updating vendored.json ..."
REPO="$REPO" TAG="$TAG" COMMIT="$COMMIT" LICENSE="$LICENSE" SKILLS_JSON="$SKILLS_JSON" \
python3 - "$ROOT/vendored.json" <<'PY'
import json, os, sys, datetime
path = sys.argv[1]
data = json.load(open(path)) if os.path.exists(path) else {}
data["superpowers"] = {
    "repo": os.environ["REPO"],
    "tag": os.environ["TAG"],
    "commit": os.environ.get("COMMIT") or None,
    "license": os.environ["LICENSE"],
    "synced": datetime.date.today().isoformat(),
    "note": "Third-party vendored methodology. Do not hand-edit vendored/superpowers/; re-run scripts/vendor-superpowers.sh.",
    "skills": json.loads(os.environ["SKILLS_JSON"]),
}
with open(path, "w") as f:
    json.dump(data, f, indent=2); f.write("\n")
PY

echo "[vendor] Done. ${REPO}@${TAG} (${COMMIT:-no-commit}) vendored to vendored/superpowers/."
echo "[vendor] Review the diff, then commit + cut a cabral-skills release tag."
